### ISSUE TITLE
Site offline

### ISSUE THREAD

**Issue by eeeschwartz** [openlexington/WhatsMyDistrict#66]
Ahoy OpenLexingtonians. We have some enthusiastic users in the council offices who mentioned that the site is down atm. 

Let us know if there's anything we can do to help on the city side.

Also, what you all doing for lunch today?

Thanks!

**Comment by chaserx** [comment]
The instance is currently failing it's health checks. There's been trouble with that AWS instance perhaps a result of the hardware. The hardware it's running on is scheduled for retirement in 7 days.

**Comment by chaserx** [comment]
I think lunch plans are open.

**Comment by eeeschwartz** [comment]
@chaserx might I stop by yr office round noon?

**Comment by chaserx** [comment]
@eeeschwartz sure thing.

**Comment by chaserx** [comment]
@mikedillion has suggested we host the application on heroku and use RDS for database as it now supports postgis.

**Comment by chaserx** [comment]
I'm going to restart the instance and see if that helps

**Comment by eeeschwartz** [comment]
Thanks y'all

**Comment by chaserx** [comment]
Update: my AWS account is currently blocked from performing actions on EC2 instances. I've been in a long email support chain for a the past 12 hours or so. Hopefully, the customer support can resolve this today.

**Comment by chaserx** [comment]
Safeguards have been lifted on my AWS account after some access keys were apparently released to the wild. A new instance has been started, elastic IPs associated, and the unicorns started. We should be good to go. @eeeschwartz please inform those council offices that WMD is back online.

**Comment by eeeschwartz** [comment]
That's excellent - thank you @chaserx!
